defmodule Terrarium.Providers.Exe do
  @moduledoc """
  A Terrarium provider for [exe.dev](https://exe.dev) virtual machines.

  Creates and manages VMs using exe.dev's HTTPS API for lifecycle operations
  and direct SSH connections to `<vmname>.exe.xyz` for command execution and
  file operations via SFTP.

  exe.dev VMs have unrestricted outbound internet access, persistent disks,
  and sub-second start times.

  ## Configuration

      config :terrarium,
        providers: [
          exe: {Terrarium.Providers.Exe,
            token: System.fetch_env!("EXE_DEV_TOKEN")
          }
        ]

  ## Options

  - `:token` — (required) exe.dev API token (`exe0.<payload>.<signature>`)
  - `:api_url` — base URL for the exe.dev API (default: `"https://exe.dev"`)
  - `:name` — VM name (optional, auto-generated if not provided)
  - `:image` — container image (default: `"boldsoftware/exeuntu"`)
  - `:env` — environment variables map (optional)
  - `:auth` — SSH authentication, same as `Terrarium.Provider.auth()`:
    - `{:key_path, path}` — path to a private key file (default: `"~/.ssh/id_ed25519"`)
    - `{:key, pem_string}` — private key as a PEM string
    - `{:password, password}` — password authentication
    - `{:user_dir, dir}` — directory containing SSH keys
    - `nil` — use default SSH key discovery
  - `:ssh_user` — SSH user for VM access (default: `"exedev"`)

  ## Authentication

  Tokens are generated by signing with your SSH key registered with exe.dev.
  See [exe.dev docs](https://exe.dev/docs/api) for token generation details.
  """

  use Terrarium.Provider

  require Logger

  @default_api_url "https://exe.dev"
  @default_image "boldsoftware/exeuntu"
  @default_ssh_user "exedev"
  @default_auth {:key_path, "~/.ssh/id_ed25519"}
  @default_exec_timeout 120_000

  @impl true
  def create(opts) do
    token = Keyword.fetch!(opts, :token)
    api_url = Keyword.get(opts, :api_url, @default_api_url)
    name = Keyword.get(opts, :name)
    image = Keyword.get(opts, :image, @default_image)
    env = Keyword.get(opts, :env, %{})
    auth = Keyword.get(opts, :auth, @default_auth)
    ssh_user = Keyword.get(opts, :ssh_user, @default_ssh_user)

    cmd_parts = ["new", "--json", "--no-email"]
    cmd_parts = if name, do: cmd_parts ++ ["--name=#{name}"], else: cmd_parts
    cmd_parts = if image == @default_image, do: cmd_parts, else: cmd_parts ++ ["--image=#{image}"]
    cmd_parts = cmd_parts ++ Enum.map(env, fn {k, v} -> "--env=#{k}=#{v}" end)

    command = Enum.join(cmd_parts, " ")

    Logger.info("Creating exe.dev VM", name: name, image: image)

    case api_request(api_url, token, command) do
      {:ok, %{"vm_name" => vm_name} = resp} ->
        Logger.info("exe.dev VM created", vm_name: vm_name)

        ssh_host = resp["ssh_dest"] || "#{vm_name}.exe.xyz"

        # Establish SSH connection for exec/file operations
        case connect_ssh(ssh_host, ssh_user, auth) do
          {:ok, conn} ->
            sandbox =
              %Terrarium.Sandbox{
                id: vm_name,
                provider: __MODULE__,
                state: %{
                  "vm_name" => vm_name,
                  "api_url" => api_url,
                  "token" => token,
                  "ssh_host" => ssh_host,
                  "ssh_user" => ssh_user,
                  "auth" => serialize_auth(auth),
                  "conn" => conn
                }
              }
              |> Map.put(:name, name || vm_name)

            {:ok, sandbox}

          {:error, reason} ->
            Logger.error("Failed to connect SSH to exe.dev VM", vm_name: vm_name, reason: reason)
            # Clean up the VM since we can't use it
            api_request(api_url, token, "rm #{vm_name} --json")
            {:error, {:ssh_connect_failed, reason}}
        end

      {:ok, resp} ->
        {:error, {:unexpected_response, resp}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def destroy(%Terrarium.Sandbox{state: state}) do
    vm_name = state["vm_name"]
    Logger.info("Destroying exe.dev VM", vm_name: vm_name)

    if state["conn"], do: :ssh.close(state["conn"])

    case api_request(state["api_url"], state["token"], "rm #{vm_name} --json") do
      {:ok, %{"deleted" => deleted}} when is_list(deleted) ->
        if vm_name in deleted, do: :ok, else: {:error, :not_deleted}

      {:ok, _} ->
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def status(%Terrarium.Sandbox{state: state}) do
    case api_request(state["api_url"], state["token"], "ls --json") do
      {:ok, %{"vms" => vms}} when is_list(vms) ->
        case Enum.find(vms, &(&1["vm_name"] == state["vm_name"])) do
          %{"status" => "running"} -> :running
          %{"status" => "starting"} -> :creating
          %{"status" => "stopping"} -> :stopped
          %{"status" => "stopped"} -> :stopped
          nil -> :destroyed
          _ -> :error
        end

      _ ->
        :error
    end
  end

  @impl true
  def reconnect(%Terrarium.Sandbox{state: state} = sandbox) do
    conn = state["conn"]

    if conn && Process.alive?(conn) do
      {:ok, sandbox}
    else
      case connect_ssh(state["ssh_host"], state["ssh_user"], deserialize_auth(state["auth"])) do
        {:ok, conn} ->
          {:ok, %{sandbox | state: Map.put(state, "conn", conn)}}

        {:error, reason} ->
          {:error, reason}
      end
    end
  end

  @impl true
  def ssh_opts(%Terrarium.Sandbox{state: state}) do
    {:ok,
     [
       host: state["ssh_host"],
       port: 22,
       user: state["ssh_user"],
       auth: deserialize_auth(state["auth"])
     ]}
  end

  @impl true
  def exec(sandbox, command, opts \\ [])

  def exec(%Terrarium.Sandbox{state: %{"conn" => conn}}, command, opts) do
    timeout = Keyword.get(opts, :timeout, @default_exec_timeout)
    cwd = Keyword.get(opts, :cwd)

    full_command = if cwd, do: "cd #{escape(cwd)} && #{command}", else: command

    case :ssh_connection.session_channel(conn, timeout) do
      {:ok, channel} ->
        :success = :ssh_connection.exec(conn, channel, to_charlist(full_command), timeout)
        collect_response(conn, channel, timeout)

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def read_file(%Terrarium.Sandbox{state: %{"conn" => conn}}, path) do
    case :ssh_sftp.start_channel(conn) do
      {:ok, sftp} ->
        result = :ssh_sftp.read_file(sftp, to_charlist(path))
        :ssh_sftp.stop_channel(sftp)
        result

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def write_file(%Terrarium.Sandbox{state: %{"conn" => conn}}, path, content) do
    case :ssh_sftp.start_channel(conn) do
      {:ok, sftp} ->
        ensure_remote_dir(sftp, Path.dirname(path))
        result = :ssh_sftp.write_file(sftp, to_charlist(path), content)
        :ssh_sftp.stop_channel(sftp)
        result

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def ls(%Terrarium.Sandbox{state: %{"conn" => conn}}, path) do
    case :ssh_sftp.start_channel(conn) do
      {:ok, sftp} ->
        result =
          case :ssh_sftp.list_dir(sftp, to_charlist(path)) do
            {:ok, entries} ->
              names =
                entries
                |> Enum.map(&to_string/1)
                |> Enum.reject(&(&1 in [".", ".."]))
                |> Enum.sort()

              {:ok, names}

            {:error, reason} ->
              {:error, reason}
          end

        :ssh_sftp.stop_channel(sftp)
        result

      {:error, reason} ->
        {:error, reason}
    end
  end

  # ============================================================================
  # HTTPS API
  # ============================================================================

  defp api_request(api_url, token, command) do
    url = "#{api_url}/exec"

    Logger.debug("exe.dev API request", command: command)

    case Req.post(url,
           body: command,
           headers: [
             {"authorization", "Bearer #{token}"},
             {"content-type", "text/plain"}
           ],
           receive_timeout: 60_000
         ) do
      {:ok, %{status: status, body: body}} when status in 200..299 ->
        case body do
          %{} = json -> {:ok, json}
          binary when is_binary(binary) -> Jason.decode(binary)
        end

      {:ok, %{status: status, body: body}} ->
        Logger.error("exe.dev API error", status: status, body: inspect(body))
        {:error, {:api_error, status, body}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # ============================================================================
  # SSH
  # ============================================================================

  defp connect_ssh(host, user, auth) do
    ssh_opts =
      [
        user: to_charlist(user),
        silently_accept_hosts: true,
        user_interaction: false
      ]
      |> add_auth_opts(auth)

    Logger.debug("Connecting SSH to exe.dev VM", host: host, user: user)

    case :ssh.connect(to_charlist(host), 22, ssh_opts, 30_000) do
      {:ok, conn} ->
        Logger.debug("SSH connected to exe.dev VM", host: host)
        {:ok, conn}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp add_auth_opts(ssh_opts, nil), do: ssh_opts

  defp add_auth_opts(ssh_opts, {:password, password}), do: Keyword.put(ssh_opts, :password, to_charlist(password))

  defp add_auth_opts(ssh_opts, {:key, pem}),
    do: Keyword.put(ssh_opts, :key_cb, {Terrarium.Providers.SSH.KeyCb, key: pem})

  defp add_auth_opts(ssh_opts, {:key_path, path}) do
    # Use user_dir with the key's parent directory so Erlang's built-in SSH
    # key discovery handles algorithm negotiation correctly (key_cb can fail
    # with some SSH proxies like SSHPiper).
    Keyword.put(ssh_opts, :user_dir, to_charlist(Path.dirname(Path.expand(path))))
  end

  defp add_auth_opts(ssh_opts, {:user_dir, dir}), do: Keyword.put(ssh_opts, :user_dir, to_charlist(Path.expand(dir)))

  defp serialize_auth(nil), do: nil
  defp serialize_auth({:password, password}), do: %{"type" => "password", "value" => password}
  defp serialize_auth({:key, pem}), do: %{"type" => "key", "value" => pem}
  defp serialize_auth({:key_path, path}), do: %{"type" => "key_path", "value" => path}
  defp serialize_auth({:user_dir, dir}), do: %{"type" => "user_dir", "value" => dir}

  defp deserialize_auth(nil), do: nil
  defp deserialize_auth(%{"type" => "password", "value" => v}), do: {:password, v}
  defp deserialize_auth(%{"type" => "key", "value" => v}), do: {:key, v}
  defp deserialize_auth(%{"type" => "key_path", "value" => v}), do: {:key_path, v}
  defp deserialize_auth(%{"type" => "user_dir", "value" => v}), do: {:user_dir, v}

  defp collect_response(conn, channel, timeout) do
    collect_response(conn, channel, timeout, %{stdout: "", stderr: "", exit_status: 0})
  end

  defp collect_response(conn, channel, timeout, acc) do
    receive do
      {:ssh_cm, ^conn, {:data, ^channel, 0, data}} ->
        collect_response(conn, channel, timeout, %{acc | stdout: acc.stdout <> data})

      {:ssh_cm, ^conn, {:data, ^channel, 1, data}} ->
        collect_response(conn, channel, timeout, %{acc | stderr: acc.stderr <> data})

      {:ssh_cm, ^conn, {:eof, ^channel}} ->
        collect_response(conn, channel, timeout, acc)

      {:ssh_cm, ^conn, {:exit_status, ^channel, status}} ->
        collect_response(conn, channel, timeout, %{acc | exit_status: status})

      {:ssh_cm, ^conn, {:closed, ^channel}} ->
        {:ok,
         %Terrarium.Process.Result{
           exit_code: acc.exit_status,
           stdout: acc.stdout,
           stderr: acc.stderr
         }}
    after
      timeout -> {:error, :timeout}
    end
  end

  defp ensure_remote_dir(sftp, path) do
    parts = Path.split(path)

    Enum.reduce(parts, "", fn part, acc ->
      dir = Path.join(acc, part)
      :ssh_sftp.make_dir(sftp, to_charlist(dir))
      dir
    end)
  end

  defp escape(str), do: "'#{String.replace(str, "'", "'\\''")}'"
end
